# level 4 --> level 5
# The password for the next level is stored in the only human-readable file in the inhere directory. Tip: if your \n
# terminal is messed up, try the “reset” command.

#username: bandit4@bandit.labs.overthewire.org
#password: 2WmrDFRmJIq3IPxneAaMGhap0pFhF3NJ

# first part of the problem is to find the human-readable file in the "inhere" directory
ls
cd inhere
find -type f | xargs file 
# find - searches for files in the current directory (-type f)
# | - gives the output of first command as an input to the next one
# xargs file - takes the list of files generated by the first command and passes them as arguments to the "file" which \n
# determines the filetype (textfile, binary, image)
# we can see that ./-file07 has the file type ASCII text (human-readable)
#./-file07 is a dashed file (check level1 for more info on dashed files)
cat < -file07 # to print dashed file  

#copy the password to ssh into your next bandit level
# use the "exit" command to exit bandit1

# Happy Hacking! 